language: node_js
dist: bionic
os: linux
node_js:
  - lts/*
addons:
  chrome: stable
install:
  - npm ci
script:
  - npm audit --production
  - npm run lint
  - npm test
  - npm run build
  - npm run lighthouse
after_success:
  - npm run coveralls
before_deploy:
  - rm .gitignore
deploy:
  strategy: git
  skip_cleanup: true
  local_dir: dist
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
